{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  {{- range $k, $v := .Values.serviceAccount.annotations }}
  annotations:
    {{ $k }}: {{ $v }}
  {{- end }}
{{- end }}
